// One-off: convert a recipes JSON file (the old in-repo format) into SQL for
// the recipe/component tables. Content stays OUT of the repo: the generated
// .sql goes to seed-data/ (gitignored) and is applied with
//   npx wrangler d1 execute CATALOG_DB [--local|--remote] --file=seed-data/recipes.sql
//
//   node catalog/scripts/import-recipes.mjs <path-to-recipes.json>

import { readFile, writeFile, mkdir } from 'node:fs/promises'

const src = process.argv[2]
if (!src) {
  console.error('usage: node catalog/scripts/import-recipes.mjs <recipes.json>')
  process.exit(1)
}
const d = JSON.parse(await readFile(src, 'utf8'))
const esc = (s) => (s == null ? 'NULL' : `'${String(s).replace(/'/g, "''")}'`)

const lines = ['-- generated by import-recipes.mjs — DO NOT COMMIT (seed-data/ is gitignored)']
for (const [id, c] of Object.entries(d.components ?? {})) {
  lines.push(
    `INSERT OR REPLACE INTO component (id, part_type, name, vendor, url, price_inr, stock, note) VALUES (` +
      `${esc(id)}, ${esc(c.category)}, ${esc(c.name)}, ${esc(c.vendor)}, ${esc(c.url)}, ${c.priceINR ?? 'NULL'}, ${esc(c.stock)}, ${esc(c.note)});`,
  )
}
for (const r of d.recipes ?? []) {
  const picks = (r.picks ?? []).map((p) => ({ role: p.role, component_id: p.id, note: p.note ?? null }))
  lines.push(
    `INSERT INTO recipe (category_id, goal, label, span_min, span_max, summary, source, picks) VALUES (` +
      `'wings', ${esc(r.goal)}, ${esc(r.label)}, ${r.appliesTo?.spanMM?.[0] ?? 'NULL'}, ${r.appliesTo?.spanMM?.[1] ?? 'NULL'}, ` +
      `${esc(r.summary)}, ${esc(r.source)}, ${esc(JSON.stringify(picks))});`,
  )
}
await mkdir(new URL('../../seed-data/', import.meta.url), { recursive: true })
const out = new URL('../../seed-data/recipes.sql', import.meta.url)
await writeFile(out, lines.join('\n') + '\n')
console.log(`wrote ${lines.length - 1} statements -> seed-data/recipes.sql`)
