// The shared editorial page shell: GA (www only), head meta, family header and footer.
// Used by scripts/seo-content.mjs (videos, methodology) and scripts/build-nanawing-pages.mjs
// (the Nanawing aircraft page). One shell, so the pages cannot drift apart. Literal asset
// URLs here carry ?v= stamps that scripts/version-assets.mjs keeps current.
import { familyNav, familyFooter } from './brand-shell.mjs';
export const site = 'https://www.narenana.com';
export const safe = value => JSON.stringify(value).replace(/</g,'\\u003c');
// head: extra tags before </head> (page CSS, preloads). scripts: extra markup before </body>.
export function page({path,title,description,body,schema,image=site+'/og.jpg',head='',scripts=''}) {
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><script>if(location.hostname==='www.narenana.com'){var ga=document.createElement('script');ga.async=true;ga.src='https://www.googletagmanager.com/gtag/js?id=G-1KY518LPBH';document.head.appendChild(ga);window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','G-1KY518LPBH')}</script><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | narenana</title><meta name="description" content="${description}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${site}${path}"><meta name="theme-color" content="#087bc1"><link rel="icon" href="/assets/avatar.jpg?v=49424a6497"><meta property="og:type" content="website"><meta property="og:site_name" content="narenana"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:url" content="${site}${path}"><meta property="og:image" content="${image}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${title}"><meta name="twitter:description" content="${description}"><meta name="twitter:image" content="${image}"><meta property="og:image:alt" content="${title}"><link rel="stylesheet" href="/assets/family/fonts.css?v=c848c473a8"><link rel="stylesheet" href="/assets/editorial.css?v=f64f49da02"><link rel="stylesheet" href="/assets/family/shell.css?v=dfbc6fd384"><script type="application/ld+json">${safe(schema)}</script>${head}</head><body><a class="skip" href="#main">Skip to content</a>${familyNav({home:'',avatar:'/assets/family/avatar.jpg?v=49424a6497'})}<main id="main">${body}</main>${familyFooter({home:''})}<script type="module" src="/assets/family/preview-links.js?v=be680653c7"></script>${scripts}</body></html>`;
}
