// Reproducible editorial SEO pages and homepage video metadata.
// Dates and durations verified against YouTube watch-page metadata, 2026-09-23.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { familyNav, familyFooter } from './brand-shell.mjs';
const site = 'https://www.narenana.com';
export const videos = [
  { slug:'nanawing-giz-fpv-review', id:'3x8sWLL6EhI', name:'Giz FPV reviews Nanawing: free FPV wing simulator', channel:'Giz FPV', channelUrl:'https://www.youtube.com/channel/UCN1gpm5NrbxMFFglrCnGsjg', uploadDate:'2026-07-25T07:27:39-07:00', duration:'PT28M12S', description:'Watch Giz FPV try Nanawing, the free browser FPV flying-wing simulator, with an RC transmitter and explore its flight controls and simulated flying experience.', body:`<h2>A wing pilot’s perspective</h2><p>Giz FPV takes Nanawing for a flight and discusses how it feels from a pilot’s perspective. Watch the original review above, then try the simulator yourself. The review belongs to Giz FPV and is embedded from their YouTube channel.</p><h2>Try what you see</h2><p>Nanawing runs in your browser with keyboard, gamepad or a compatible RC radio. New pilots can practise launches, turns and landings; experienced pilots can fly the gate courses and compare their best laps.</p><p><a class="button" href="https://sim.narenana.com/">Launch Nanawing ↗</a></p><nav class="related" aria-label="Related guides"><a href="https://sim.narenana.com/guides/how-to-play">Controls and first-flight guide ↗</a><a href="https://sim.narenana.com/leaderboard/">Current race standings ↗</a><a href="/#nanawing-2">Explore Nanawing 2, the line-of-sight simulator →</a></nav>` },
  { slug:'log-viewer-walkthrough', id:'6MLQCoG5t2w', name:'EdgeTX Log Viewer & Visualiser — video walkthrough', channel:'narenana', channelUrl:'https://www.youtube.com/@narenana', uploadDate:'2026-04-23T09:37:55-07:00', duration:'PT2M16S', description:'Watch narenana demonstrate the EdgeTX Log Viewer & Visualiser, then open the browser tool to explore your radio telemetry and flight logs.', body:`<h2>See the flight behind the numbers</h2><p>This short walkthrough introduces the EdgeTX Log Viewer & Visualiser. Watch how the tool presents a flight, then open your own logs in the viewer.</p><h2>Explore your logs</h2><p>The current viewer supports EdgeTX radio CSV logs and Betaflight/iNAV Blackbox logs. Available charts and 3D replay depend on the fields recorded in your file. Log processing happens locally in your browser.</p><p><a class="button" href="/log-viewer/">Open the log viewer →</a></p><nav class="related" aria-label="Related guides"><a href="/log-viewer/edgetx-log-viewer/">Open EdgeTX radio logs →</a><a href="/log-viewer/inav-blackbox-viewer/">Explore iNAV Blackbox logs →</a><a href="/log-viewer/guides/">Read the flight-log guides →</a></nav>` },
];
const videoObject = v => ({'@type':'VideoObject','@id':`${site}/videos/${v.slug}/#video`,name:v.name,description:v.description,thumbnailUrl:[`https://i.ytimg.com/vi/${v.id}/hqdefault.jpg`],uploadDate:v.uploadDate,duration:v.duration,embedUrl:`https://www.youtube-nocookie.com/embed/${v.id}`,url:`${site}/videos/${v.slug}/`,author:{'@type':'Person',name:v.channel,url:v.channelUrl}});
const safe = value => JSON.stringify(value).replace(/</g,'\\u003c');
function page({path,title,description,body,schema,image=site+'/og.jpg'}) {
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | narenana</title><meta name="description" content="${description}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${site}${path}"><meta name="theme-color" content="#087bc1"><link rel="icon" href="/assets/avatar.jpg?v=49424a6497"><meta property="og:type" content="website"><meta property="og:site_name" content="narenana"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:url" content="${site}${path}"><meta property="og:image" content="${image}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${title}"><meta name="twitter:description" content="${description}"><meta name="twitter:image" content="${image}"><meta property="og:image:alt" content="${title}"><link rel="stylesheet" href="/assets/family/fonts.css?v=c848c473a8"><link rel="stylesheet" href="/assets/editorial.css?v=f64f49da02"><link rel="stylesheet" href="/assets/family/shell.css?v=79d618fb95"><script type="application/ld+json">${safe(schema)}</script></head><body><a class="skip" href="#main">Skip to content</a>${familyNav({home:'',avatar:'/assets/family/avatar.jpg?v=49424a6497'})}<main id="main">${body}</main>${familyFooter({home:''})}<script type="module" src="/assets/family/preview-links.js?v=be680653c7"></script></body></html>`;
}
for(const v of videos) {
 const path=`/videos/${v.slug}/`;
 const graph=[videoObject(v),{'@type':'WebPage','@id':site+path,url:site+path,name:v.name,mainEntity:{'@id':site+path+'#video'}},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:site+'/'},{'@type':'ListItem',position:2,name:v.name,item:site+path}]}];
 const body=`<nav class="crumbs" aria-label="Breadcrumb"><a href="/">Home</a> / Video</nav><h1>${v.name}</h1><p class="lede">${v.description}</p><div class="watch-player"><iframe src="https://www.youtube-nocookie.com/embed/${v.id}?rel=0" title="${v.name}" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div><p class="credit">By <a href="${v.channelUrl}">${v.channel}</a> · Published <time datetime="${v.uploadDate}">${v.uploadDate.slice(0,10)}</time> · <a href="https://www.youtube.com/watch?v=${v.id}">Watch on YouTube ↗</a></p>${v.body}`;
 mkdirSync(`site${path}`,{recursive:true});writeFileSync(`site${path}index.html`,page({path,image:`https://i.ytimg.com/vi/${v.id}/hqdefault.jpg`,title:v.name,description:v.description,body,schema:{'@context':'https://schema.org','@graph':graph}}));
}
const methodPath='/catalog-methodology/';
mkdirSync('site'+methodPath,{recursive:true});
writeFileSync('site'+methodPath+'index.html',page({path:methodPath,title:'How Wings checks prices, stock and listings',description:'How the Wings RC aircraft catalog collects Indian seller listings, checks prices and availability, and handles uncertain or outdated information.',schema:{'@context':'https://schema.org','@type':'WebPage',url:site+methodPath,name:'Wings catalog methodology'},body:`<nav class="crumbs" aria-label="Breadcrumb"><a href="/">Home</a> / <a href="/wings/">Wings</a> / Catalog checks</nav><h1>Prices and stock, with the checks explained.</h1><p class="lede">Wings compares RC aircraft listings from Indian sellers. You buy from the seller; narenana does not take payment or fulfil the order.</p><h2>What gets listed</h2><p>Only approved listings linked to a published aircraft model appear in the catalog. We group listings by aircraft and show configuration, pack quantity and condition where available. Approval is a catalog review, not a guarantee of a seller’s service, warranty or delivery.</p><h2>How prices and stock are refreshed</h2><p>The pipeline scans active seller sources in daily sweeps and checks approved product pages, prioritising older checks. Jobs run in small scheduled batches. A full refresh can take longer when a seller blocks access, a queue is busy or checks are paused.</p><p>Each seller row shows the date its data was last checked or seen. These are observations from a seller’s page, not a promise of checkout availability. Open the seller’s listing to confirm the final price, stock, shipping and taxes.</p><h2>When information is uncertain</h2><p>Large price changes and product-identity mismatches are flagged for review. A listing under review keeps its stock status, but its price is withheld and shown as “Price under review” until it is checked. Missing prices stay blank, and unavailable or removed offers are labelled separately. Product pages can remain useful when every seller is temporarily out of stock.</p><h2>Compare like with like</h2><p>A kit, PNP aircraft, ready-to-fly package and multi-pack can include very different equipment. Check the configuration and condition before comparing totals. Used listings are labelled separately when the source identifies them.</p><h2>Spotted a mismatch?</h2><p><a href="/#contact">Contact narenana</a> with the aircraft and seller links so the listing can be checked.</p><p><a class="button" href="/wings/">Find your next favourite RC wing →</a></p>`}));
let home=readFileSync('site/index.html','utf8');
home=home.replace(/<meta name="description" content="[^"]*"\s*\/>/,'<meta name="description" content="Fly Nanawing, the free browser FPV wing simulator. Try Nanawing 2, compare RC wings in India, and explore your flight logs." />');
home=home.replace(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/,(_,raw)=>{
 const data=JSON.parse(raw); const description='Nanawing FPV and Nanawing 2 line-of-sight simulators, RC aircraft price comparisons for India, flight-log tools and videos by narenana.';
 for(const entry of data['@graph'])if(['Organization','WebSite'].includes(entry['@type']))entry.description=description;
 data['@graph']=data['@graph'].filter(entry=>entry['@type']!=='VideoObject');data['@graph'].push(...videos.map(videoObject));
 return '<script type="application/ld+json">'+JSON.stringify(data,null,2).replace(/</g,'\\u003c')+'</script>';
});
if(!home.includes('/assets/family/fonts.css?v=c848c473a8') && !home.includes('fonts.googleapis.com/css2'))home=home.replace('    <link rel="stylesheet" href="/assets/home.css?v=3e44052424',`    <link rel="preconnect" href="https://fonts.googleapis.com" />\n    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />\n    <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@600;700;800&amp;family=DM+Sans:wght@400;500;600;700&amp;family=JetBrains+Mono:wght@400;500&amp;display=swap" rel="stylesheet" />\n    <link rel="stylesheet" href="/assets/home.css?v=3e44052424`);
home=home.replace('The latest prices and stock status from dozens of verified Indian sellers. Compare your favourite RC wings in one place, then head straight to the seller.','Compare the latest checked prices and stock from Indian sellers. Find your favourite RC wing, compare the listings, then head straight to the seller.');
home=home.replace('Dozens of verified Indian sellers','<span id="catalog-seller-count">Reviewed Indian seller listings</span>');
if(!home.includes('href="/catalog-methodology/"'))home=home.replace('<div class="catalog-promise"','<p class="catalog-method"><a href="/catalog-methodology/">How we check listings, prices and stock ↗</a></p>\n        <div class="catalog-promise"');
if(!home.includes('href="/videos/nanawing-giz-fpv-review/"'))home=home.replace('<span>GIZ FPV × NANAWING · FULL REVIEW</span>','<a href="/videos/nanawing-giz-fpv-review/">Giz FPV review &amp; flight guides →</a>');
if(!home.includes('href="/videos/log-viewer-walkthrough/"'))home=home.replace('<span>WATCH THE TOOL IN ACTION</span>','<a href="/videos/log-viewer-walkthrough/">Walkthrough &amp; log guides →</a>');
writeFileSync('site/index.html',home);
let css=readFileSync('site/assets/home.css','utf8').replace(/^@import[^\n]*\r?\n/,'');
if(!css.includes('.catalog-method{'))css+='\n.catalog-method{font-size:12px;color:var(--blue)}.catalog-method a{text-decoration:underline;text-underline-offset:3px}.shopc-checked{font:9px/1.5 var(--mono);color:var(--muted);margin:10px 0 0}\n';
writeFileSync('site/assets/home.css',css);
const manifest=JSON.parse(readFileSync('site/manifest.json','utf8'));Object.assign(manifest,{name:'narenana — Nanawing & RC flying tools',description:'Fly Nanawing FPV and Nanawing 2, compare RC aircraft in India and explore your flight logs.',theme_color:'#087bc1',background_color:'#f4f8fc'});writeFileSync('site/manifest.json',JSON.stringify(manifest,null,2)+'\n');
// These pages, site/index.html and home.css were just rewritten: re-stamp every
// asset version so the generator and scripts/version-assets.mjs never disagree.
const { planAssetVersions } = await import('./version-assets.mjs');
{ const plan = planAssetVersions(); for (const f of plan.changes) writeFileSync(f, plan.text.get(f)); if (plan.manifestStale) writeFileSync(new URL('../src/asset-versions.mjs', import.meta.url), plan.manifest); }
