// Stamp every reference to a file under site/assets/ with a hash of that
// file's content (?v=<hash>), and write src/asset-versions.mjs so the Worker
// can serve exactly those URLs as immutable.
//
//   npm run assets:version          rewrite references + manifest
//   npm run assets:version -- --check   exit 1 if anything is stale (CI / tests)
//
// Run it after editing anything in site/assets/ or any page that links to it.
// Files that reference other assets (fonts.css → *.woff2, preview-links.js →
// share.js) are hashed AFTER their own references are stamped, so a change to a
// font changes fonts.css's version too. Iterates to a fixed point.
import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { join, relative, dirname, posix } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SITE = join(ROOT, 'site')
const ASSETS = join(SITE, 'assets')
const MANIFEST = join(ROOT, 'src', 'asset-versions.mjs')
const HASH_LEN = 10

const walk = (dir, keep) => readdirSync(dir).flatMap((name) => {
  const p = join(dir, name)
  return statSync(p).isDirectory() ? walk(p, keep) : keep(p) ? [p] : []
})
// Every extension actually present under site/assets (avif, txt, …), so a new
// file type is versioned too instead of silently staying unversioned.
const EXT = [...new Set(walk(ASSETS, () => true).map((p) => (p.match(/\.([A-Za-z0-9]+)$/) || [])[1]).filter(Boolean))]
  .sort((a, b) => b.length - a.length).join('|')
const posixPath = (p) => p.split('\\').join('/')
// URL path of a file under site/ ("/assets/family/fonts.css").
const urlOf = (abs) => '/' + posixPath(relative(SITE, abs))

// Files whose TEXT may contain references. Generated catalog CSS (styles.mjs)
// only references its own /catalog.css version and is left to gen-styles.
const referrers = () => [
  ...walk(SITE, (p) => /\.(html|json)$/.test(p)),
  ...walk(ASSETS, (p) => /\.(css|js|mjs)$/.test(p)),
  ...walk(join(ROOT, 'catalog', 'lib'), (p) => /\.mjs$/.test(p) && !p.endsWith('styles.mjs')),
  ...walk(join(ROOT, 'src'), (p) => /\.js$/.test(p) || (/\.mjs$/.test(p) && p !== MANIFEST)),
  // Editorial page generator: its template must carry the same versions, or a
  // re-run would regenerate the video/methodology pages with stale links.
  join(ROOT, 'scripts', 'seo-content.mjs'),
]

// Absolute (/assets/x.css, https://www.narenana.com/assets/x.css) and, inside
// site/assets files, relative (./x.woff2, ../x.js) references, with any
// existing ?v= label.
const ABS = new RegExp(`(?<![A-Za-z0-9_.\\-/])(https://www\\.narenana\\.com)?/assets/([A-Za-z0-9_./-]+?\\.(?:${EXT}))(\\?v=[A-Za-z0-9._-]*)?(?![A-Za-z0-9_./-])`, 'g')
const REL = new RegExp(`(?<=url\\(\\s*['"]?|from\\s*['"]|import\\s*['"]|import\\(\\s*['"]|new\\s+URL\\(\\s*['"])(\\.{1,2}/[A-Za-z0-9_./-]+?\\.(?:${EXT}))(\\?v=[A-Za-z0-9._-]*)?(?![A-Za-z0-9_./-])`, 'g')

export function planAssetVersions() {
  const files = referrers()
  const text = new Map(files.map((f) => [f, readFileSync(f, 'utf8')]))
  const assetFiles = walk(ASSETS, () => true)
  // Hash text with LF line endings: a Windows checkout (core.autocrlf) holds
  // CRLF while the repo and the Linux deploy build hold LF, and the same file
  // must get the same version on every machine. Binary files hash raw.
  const TEXT = /\.(css|js|mjs|svg|json|html|txt)$/
  const bytes = (abs) => {
    if (!TEXT.test(abs)) return readFileSync(abs)
    const s = text.has(abs) ? text.get(abs) : readFileSync(abs, 'utf8')
    return Buffer.from(s.replace(/\r\n/g, '\n'))
  }
  const missing = new Set()
  let versions = {}
  for (let pass = 0; pass < 12; pass++) {
    versions = Object.fromEntries(assetFiles.map((abs) => [urlOf(abs), createHash('sha256').update(bytes(abs)).digest('hex').slice(0, HASH_LEN)]))
    let changed = false
    for (const f of files) {
      const before = text.get(f)
      let after = before.replace(ABS, (all, host = '', path) => {
        const v = versions['/assets/' + path]
        if (!v) { missing.add('/assets/' + path + '  (in ' + posixPath(relative(ROOT, f)) + ')'); return all }
        return `${host}/assets/${path}?v=${v}`
      })
      if (f.startsWith(ASSETS)) {
        after = after.replace(REL, (all, rel) => {
          const target = '/' + posix.normalize(posix.join(posix.dirname(urlOf(f).slice(1)), rel))
          const v = versions[target]
          if (!v) { missing.add(target + '  (in ' + posixPath(relative(ROOT, f)) + ')'); return all }
          return `${rel}?v=${v}`
        })
      }
      if (after !== before) { text.set(f, after); changed = true }
    }
    if (!changed) break
    if (pass === 11) throw new Error('asset versions did not converge (reference cycle?)')
  }
  const manifest = '// Generated by scripts/version-assets.mjs — do not edit. Content hashes of\n' +
    '// files under site/assets/, used to serve exactly these ?v= URLs as immutable.\n' +
    'export const ASSET_VERSIONS = ' + JSON.stringify(Object.fromEntries(Object.entries(versions).sort()), null, 2) + '\n'
  // Any ?v= label on an asset reference that is still not a content hash is a
  // reference form the patterns above don't cover (it would never be immutable
  // and never change on edit). Report it rather than let it pass silently.
  const LABEL = new RegExp(`[A-Za-z0-9_./-]+\\.(?:${EXT})\\?v=(?![0-9a-f]{${HASH_LEN}}(?![A-Za-z0-9._-]))[A-Za-z0-9._-]+`, 'g')
  const unhashed = files.flatMap((f) => (text.get(f).match(LABEL) || []).map((m) => m + '  (in ' + posixPath(relative(ROOT, f)) + ')'))
  const changes = files.filter((f) => text.get(f) !== readFileSync(f, 'utf8'))
  let manifestStale = true
  try { manifestStale = readFileSync(MANIFEST, 'utf8').replace(/\r\n/g, '\n') !== manifest } catch {}
  return { text, changes, manifest, manifestStale, missing: [...missing].sort(), unhashed: [...new Set(unhashed)].sort(), versions }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const plan = planAssetVersions()
  const stale = [...plan.changes.map((f) => posixPath(relative(ROOT, f))), ...(plan.manifestStale ? ['src/asset-versions.mjs'] : [])]
  if (plan.missing.length) console.warn('References to files that do not exist under site/assets (left unchanged):\n  ' + plan.missing.join('\n  '))
  if (plan.unhashed.length) console.warn('Asset references whose ?v= label is not a content hash (reference form not recognised):\n  ' + plan.unhashed.join('\n  '))
  if (process.argv.includes('--check')) {
    // Also the deploy gate ([build] in wrangler.toml): the Worker serves
    // current-hash URLs as immutable for a year, so stale or broken references
    // must never reach production.
    if (stale.length) console.error('Asset versions are stale. Run: npm run assets:version\n  ' + stale.join('\n  '))
    if (stale.length || plan.missing.length || plan.unhashed.length) process.exit(1)
    console.log(`Asset versions current (${Object.keys(plan.versions).length} files).`)
  } else {
    for (const f of plan.changes) writeFileSync(f, plan.text.get(f))
    if (plan.manifestStale) writeFileSync(MANIFEST, plan.manifest)
    console.log(stale.length ? 'Updated:\n  ' + stale.join('\n  ') : 'Already current.')
  }
}
